CREATE TABLE recipes (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
photo VARCHAR(255) NOT NULL,
ingredients TEXT[] NOT NULL,
instructions TEXT[] NOT NULL,
about TEXT[] NOT NULL,
category VARCHAR(255) NOT NULL
);

INSERT INTO recipes (title, photo, ingredients, instructions, about, category) 
VALUES (
    'Queso fundido (Mexican cheese fondue)', 
    'https://images.ctfassets.net/lwwf0cid7sw8/HJBY2tufZZS06dDtOoyKq/c3a83a8cec0310745c8d1cdd354009cd/22245995_web1_L-Queso-Fundido-edh-200804.jpg', ARRAY[ '6 waxy potatoes (such as pontiac or desiree), scrubbed (unpeeled)', '90ml olive oil, plus extra to brush', '1 teaspoon sweet paprika', '1 chorizo, casing removed, finely chopped', '2 1/2 cups (300g) grated cheddar', '1 1/4 cups (125g) grated mozzarella', '3 teaspoons cornflour', '1 onion, finely chopped', '1 1/4 cups (310ml) lager', 'Handful coriander leaves, chopped' ],
    ARRAY[ 'Preheat oven to 190°C. To make potato skins, prick potatoes all over with a fork and brush with oil. Place on a baking tray and bake for 1 1/2 hours or until tender. Remove from oven and cool slightly.', 'Cut the potatoes in half lengthways, then, using a spoon, scoop out the centre to create a hollow shell shape (the potato can be reserved to make mash).', 'Combine paprika and 2 tablespoons oil in a bowl, then brush over the potato skins and bake for a further 15-20 minutes until crisp.', 'Meanwhile, heat 2 teaspoons oil in a frypan over medium heat. Add chorizo and fry, stirring, for 3-4 minutes until crisp. Drain chorizo on paper towel, reserving oil.', 'To make the queso fundido, place the cheddar, mozzarella and cornflour in a bowl and toss to coat. Heat the remaining 2 tablespoons oil in a saucepan over medium heat. Cook onion, stirring, for 3-4 minutes until softened.', 'Add the beer and bring to a simmer, then cook for 2-3 minutes until slightly reduced. Reduce heat to low, then gradually add cheese mixture, stirring constantly until melted.' ],
    ARRAY[ '10 min', '2 hr', '6', 'easy' ], 
    'Botanas'
), (
    'Cheesy nachos', 
    'https://images.ctfassets.net/lwwf0cid7sw8/6vMqMGOVtbfI8xPE8Llarp/fd818034fe15b469790426d50df1cedf/matt-prestons-one-pot-cheesy-nachos-163985-2.jpg', ARRAY[ '2 tbs extra virgin olive oil', '1.2kg beef mince', '2 onions, finely chopped', '4 garlic cloves, thinly sliced', '2 red capsicums, cut into 2cm pieces', '1 tbs ground coriander', '2 tbs ground cumin', '2 tsp dried oregano', '1 long red chilli, thinly sliced (or to taste)', '1/4 cup (90g) tomato paste', '800g ripe tomatoes, chopped', '2 x 400g cans kidney beans, rinsed and drained', '2 cups (500ml) beef stock', '1 bunch coriander, leaves picked, stems finely sliced', '2 x 170g packets double cheese corn chips', '2 cups (240g) coarsely grated cheese (mozzarella and cheddar)', '2 jalapenos, deseeded, sliced', 'Lime wedges, to serve', 'Sour cream, to serve', 'Guacamole, to serve' ],
    ARRAY[ 'Heat oil in a large heavy-based ovenproof saucepan over high heat. Add mince and cook, breaking up lumps with a wooden spoon, for 5-6 minutes until golden brown. Reduce heat to low, add onion and cook for 4-5 minutes until soft.', 'Add garlic and capsicum and cook for 2 minutes or until fragrant. Add the spices, red chilli and tomato paste and cook for 1 minute until fragrant.', 'Add tomatoes, 1 can of beans and the stock. Bring to the boil, then reduce to a simmer, cover with a lid and cook for 1 hour or until reduced and thickened.', 'Preheat oven to 180°C.', 'Chop half the coriander leaves and stir through the mince mixture, along with the remaining can of beans. Remove from the heat. Carefully stud with corn chips, standing them upright (pointing upwards and ightly packed).', 'Mix cheese with the coriander stems, then sprinkle over the chips. Place in the oven and bake for 10-12 minutes until the cheese has melted and the chips have warmed.', 'Top with jalapeno and remaining whole coriander leaves. Serve with lime wedges, sour cream and guacamole alongside.' ],
    ARRAY[ '15 min', '25 min', '8', 'easy' ], 
    'Botanas'
), (
    'Slow-cooked chicken with brown rice', 
    'https://images.ctfassets.net/lwwf0cid7sw8/ym5CTdvVizGidRt505XoC/572d18a2c93a9cd486bb3d0dd57f0f2b/slow-cooked-chicken-with-brown-rice-and-avocado-47379-2.jpg', ARRAY[ '1 tbs olive oil', '1 whole chicken, quartered (use kitchen scissors or poultry shears to do this)', '1 onion, chopped', '1 bunch coriander, leaves picked, roots cleaned and chopped', '4 garlic cloves, peeled', '1 tsp each dried oregano, ground cumin and dried chilli flakes', '1 1/2 tsp smoked paprika (pimenton)', '2 tbs tomato paste', '6 roma tomatoes, roughly chopped', '500ml chicken stock', 'Steamed brown rice, sliced avocado, shredded spring onion, micro coriander and canned tomatillo (Mexican tomatoes – from selected grocers), to serve' ],
    ARRAY[ 'Heat the oil in a large saucepan over medium-high heat and season chicken with salt. Cook chicken pieces, skin-side down, for 6 minutes or until skin is golden. Turn, then cook for a further 4 minutes or until golden. Remove from pan and set aside.', 'Add the onion, coriander root and garlic to the same pan and cook, stirring, for 5 minutes or until softened.', 'Add dried oregano, spices and tomato paste, and cook, stirring, for 2 minutes or until fragrant. Add tomato and stir to coat, then add stock and bring to the boil.', 'Return chicken to pan, cover with a lid and reduce heat to medium-low. Simmer, stirring occasionally, for 1 hour 30 minutes or until chicken is very tender.', 'Remove chicken from pan and set aside. Increase heat to medium and simmer, uncovered, for a further 15 minutes to thicken. Season.', 'Remove skin from chicken, then shred the meat, discarding bones. Return chicken to sauce, stirring to warm through.', 'Serve with rice, avocado, tomatillo, and mixed micro coriander and spring onion.' ],
    ARRAY[ '20 min', '2 hr', '4', 'easy' ], 
    'Platillos'
), (
    'Chilli con carne with spiced guacamole', 
    'https://images.ctfassets.net/lwwf0cid7sw8/6fSxuX8kq0VON6lsCJlzHu/00a7b64d6c91df79c5a8621ba426582a/chilli-con-carne-with-spiced-guacamole-35646-2.jpg', 
    ARRAY[ '2 tbs olive oil', '1 onion, finely chopped', '2 garlic cloves, chopped',  '500g lean beef mince', '2 chillies in adobo sauce, chopped, plus 2 tbs adobo sauce', '2 tbs tomato paste', '1 tsp ground cumin', '1 tsp smoked paprika (pimenton)', '1 cup (250ml) beef stock', '400g can chopped tomatoes', '400g can red kidney beans, rinsed, drained', 'Sour cream, flour tortillas, lime wedges and micro coriander, to serve', '2 avocados, chopped', 'Juice of 1 lime, plus extra wedges to serve', '1 tsp hot paprika', '1/2 tsp ground cumin' ],
    ARRAY[ 'Heat oil in a large saucepan over medium heat. Add onion and cook, stirring, for 2-3 minutes until softened.', 'Add garlic and cook for 1 minute or until fragrant.', 'Add beef and cook, breaking up with a spoon, for 2-3 minutes until browned.', 'Add the chopped chillies, tomato paste, cumin and paprika, and cook, stirring, for a further 1 minute or until fragrant.', 'Add the stock and chopped tomatoes. Season and bring to a simmer, reduce heat to low and cook for 25-30 minutes until reduced. Add beans and stir to warm through.', 'Meanwhile, for guacamole, combine all ingredients in a bowl. Season with salt. Serve chilli con carne with guacamole, sour cream, tortillas, lime wedges and micro coriander leaves.' ],
    ARRAY[ '20min', '25min', '4', 'easy'], 
    'Platillos'
), (
    'Chicken tacos with charred corn', 
    'https://images.ctfassets.net/lwwf0cid7sw8/25yLZmi7QMTbG4TNjW2Vnc/7b8de1bc6759ba376ac4713aa96b232f/chicken-tacos-with-charred-corn-and-pineapple-salsa-77026-2.jpg', 
   ARRAY[ '600g skinless chicken thigh fillets, thickly sliced', '12 small soft tortillas, warmed', '1 avocado, cut into 1cm-thick slices', 'Pickled jalapenos, lime cheeks and hot sauces, to serve', '1 garlic clove, finely chopped', '2 long red chillies, finely chopped', '3 coriander stalks, finely chopped', '1 tsp finely grated ginger', '1 tsp each cumin and coriander seeds, toasted', '2 tbs extra virgin olive oil', '2 tbs extra virgin olive oil', '1/2 small pineapple, peeled, core removed, halved', '2 corn cobs, husks removed', 'Finely grated zest of 1 lime and juice of 2 limes', '1 jalapeno, finely chopped', '1 cup loosely packed coriander leaves, finely chopped, plus extra to serve', '1 red onion, finely chopped' , '1 tsp soy sauce'  ],
    ARRAY[ 'For the marinade, place all ingredients in a small food processor and whiz to a coarse paste. Stir through 1 tsp salt flakes and a pinch of ground black pepper. Combine marinade and chicken in a bowl, cover and chill for 2 hours or overnight to marinate.', 'For the pineapple salsa, heat a chargrill pan or barbecue to high heat. Rub oil into pineapple and corn, and grill, turning, for 15-20 minutes or until charred.', 'Set aside to cool. Once cool enough to handle, chop pineapple into 1cm pieces and cut kernels from cob, then combine in a bowl with remaining ingredients. Set aside.', 'Add the chicken to hot pan and grill for 4 minutes each side or until cooked through.', 'Fill tortillas with chicken, salsa, avocado and extra coriander. Serve with pickled jalapenos, lime cheeks and hot sauces.' ],
    ARRAY[ '15min', '30min', '2', 'easy' ], 
    'Platillos'
), (
    'Tostadas de Salpicon (shredded beef tostadas)', 
    'https://images.ctfassets.net/lwwf0cid7sw8/1mZiJ5Og6qPgLHkbm6I1RA/9c97a13d440ff7fb84d5a56dd450e575/tostadas-de-salpicon-shredded-beef-tostadas-201061-2.jpg', ARRAY[ '300g cooked beef flank, shredded (see note)', '1/4 cup (60ml) extra virgin olive oil', '1/3 cup (80ml) white wine vinegar', '1 tomato, finely chopped', '3 radishes, very thinly sliced (we used a mandoline)', '1/3 cup firmly packed roughly chopped coriander leaves', 'Chopped avocado, corn chips, crumbled queso fresco (from specialty grocers, substitute Greek-style feta) and pickled jalapenos, to serve' ],
    ARRAY[ 'Place beef in a large bowl with the oil and vinegar. Season with salt flakes and freshly ground black pepper and mix well. Leave to stand for 10 minutes. Add tomato, radish and coriander.', 'Gently toss to combine. Chill for at least 20 minutes, stirring occasionally. Check seasoning. To assemble, place some avocado on a corn chip and top with shredded beef mixture. Sprinkle with cheese and serve with jalapenos.' ],
    ARRAY[ '10min', '5 min', '10', 'medium' ], 
    'Botanas'
), (
    'Tacos de Carne Asada', 
    'https://images.ctfassets.net/lwwf0cid7sw8/2SNn0CxWaEf948TyNjcgak/9beb838b115af2fccd27bc678ae320cf/tacos-de-carne-asada-53513-2.jpg', 
    ARRAY[ '2 x 400g rib-eye steaks (bone in), at room temperature', '8 white corn tortillas', '1/2 cup shredded iceberg lettuce', 'Sour cream, coriander leaves, thinly sliced radish (we used watermelon radishes), and lime wedges, to serve', '1 avocado, chopped', '1 bunch coriander, leaves picked', '1 small red chilli, chopped', '1/2 small garlic clove, chopped', '1 Asian (red) eschalot, chopped', 'Juice of 2 limes', '1 tomato, finely chopped', '1 red onion, finely chopped', '1/2 bunch coriander, leaves picked, finely chopped', 'Juice of 1/2 a lime' ],
    ARRAY[ 'For the guacamole, whiz all ingredients in a food processor until smooth. Cover surface with plastic wrap and chill until needed.', 'For the pico de gallo, combine all ingredients in a bowl. Chill until needed.', 'Heat a chargrill pan or barbecue to high heat. Add beef and grill, turning every 10 seconds, for 10-11 minutes for medium-rare (a meat thermometer inserted into the centre will read 54°C), or until cooked to your liking.', 'Transfer to a plate and set aside, loosely covered with foil, for 10 minutes to rest.', 'Meanwhile, grill tortillas for 1 minute each side or until warmed through, then wrap in a clean tea towel to keep warm.', 'Spread warm tortillas with guacamole and top with sliced beef, lettuce, pico de gallo and sour cream. Add coriander and radish, and serve with lime wedges.' ],
    ARRAY[ '10 min', '15 min', '4', 'easy' ], 
    'Platillos'
), (
    'Sticky pork neck soft tacos', 
    'https://images.ctfassets.net/lwwf0cid7sw8/19ZZ6UrYzn7Tl98iPsB9e5/b8fe4b0cb43e9014780bc279d9826968/sticky-pork-neck-soft-tacos-with-pickled-cabbage-76743-2.jpg', 
    ARRAY[ '800g pork neck, cut into four 3cm pieces', '2 tbs each light soy sauce, runny honey & apple cider vinegar', '1/3 cup (80ml) sunflower oil', '2 tomatoes, halved, thinly sliced', '1/2 red onion, thinly sliced', 'Finely grated zest & juice of 1 lemon', '12 small white tortillas, warmed', '1 avocado, cut into wedges', 'Coriander sprigs, to serve', '300g red cabbage, shredded', '1 tsp coriander seeds, toasted, crushed', '1/3 cup (80ml) apple cider vinegar', '1 tbs runny honey' ],
    ARRAY[ 'Preheat the oven to 180°C. Grease a baking tray and line with baking paper.', 'Place pork, soy, honey, vinegar and 2 tbs oil in a bowl and toss to combine. Stand for 5 minutes to marinate.', 'Meanwhile, for the pickled cabbage, place cabbage in a heatproof bowl. Combine coriander seeds, vinegar and honey in a saucepan over high heat and bring to the boil. Pour over cabbage, stir to combine, then stand for 15 minutes to pickle slightly.', 'Meanwhile, toss tomato, onion and lemon zest and juice in a bowl.', 'To cook the pork, heat remaining 2 tbs oil in a large frypan over mediumhigh heat. In 2 batches, add pork and cook, turning halfway, for 5 minutes or until golden brown. Transfer to prepared tray and repeat with remaining pork.', 'Pour any remaining marinade over pork and roast for 8-10 minutes or until just cooked through. Stand for 10 minutes to rest.', 'Slice pork and serve on tortillas with pickled cabbage, tomato and avocado. Scatter with coriander and drizzle with pork cooking juices to serve.' ],
    ARRAY[ '20 min', '10 min', '12', 'easy' ],
    'Platillos'
), (
    'Mexican eggs with potato hash', 
    'https://images.ctfassets.net/lwwf0cid7sw8/3JTsU3LZAmh6glbbnpp9NX/83d19d06048703dd9524a0c76d7da7f0/mexican-eggs-with-potato-hash-14587-1.jpg', 
    ARRAY[ '1/4 cup (60ml) olive oil', '1 onion, finely chopped', '400g beef mince', '1/4 cup (60ml) chipotle chilli sauce (see notes) or other hot sauce', '400g can chopped tomatoes', '1/3 cup roughly chopped coriander, plus extra to serve', '1kg (about 4) desiree potatoes (unpeeled), scrubbed, coarsely grated', '50g unsalted butter, melted', '4 eggs', '1 jalapeno chilli or long green chilli, thinly sliced' ],
    ARRAY[ 'Heat 1 tablespoon oil in a large frypan (with a lid) over medium-high heat. Add onion and a pinch of salt, then cook, stirring, for 3-4 minutes until soft. Add the beef and cook, stirring, for 5 minutes or until browned.', 'Stir in the chipotle sauce, tomatoes and coriander, season with freshly ground black pepper and reduce heat to medium. Cook for a further 5-6 minutes until slightly thickened.', 'Meanwhile, to make the potato hash, place grated potato in a clean tea towel and squeeze to remove excess water. Place potato in a bowl with the melted butter, then season and stir to combine.', 'Heat another 1 tablespoon oil in a separate frypan over medium heat. Using a 1/3 cup (80ml) measuring cup, place 4 mounds of potato in the pan, flatten with a spoon and cook for 3-4 minutes each side until golden and cooked through.', 'Repeat with the remaining 1 tablespoon oil and potato mixture.', 'Using a spoon, make 4 indents in the beef, then crack an egg into each. Cover and cook for 7 minutes or until whites are cooked. Garnish with the chilli and extra coriander, then serve with the hash.' ],
    ARRAY[ '15 min', '25 min', '4', 'medium' ], 
    'Botanas'
), (
    'Rajas con crema', 
    'https://images.ctfassets.net/lwwf0cid7sw8/2SNn0CxWaEf948TyNjcgak/9beb838b115af2fccd27bc678ae320cf/tacos-de-carne-asada-53513-2.jpg', 
    ARRAY[ '500g large poblano chillies', '2 tbs vegetable oil', '1 large onion, thinly sliced', '300ml thickened cream', '100g mozzarella', 'Corn chips, to serve' ],
    ARRAY[ 'Using tongs, hold chillies directly over an open flame on a gas stove or barbecue grill, blackening and blistering the skin on all sides.', 'Keep turning until entire chilli is charred, about 8-10 minutes. Be careful, as you don’t want the chilli to be overcooked; you just need to loosen the skin for peeling.', 'Transfer chillies to a medium heatproof bowl and cover with plastic wrap, or use a large airtight container with a lid. Stand for 40 minutes or until cooled.', 'This steams the chillies, making the skin come off easily. Discard charred skin and seeds. Slice chillies into long strips and set aside.', 'Heat the vegetable oil in a deep, medium frypan over medium heat. Cook the onion, stirring occasionally, for about 7 minutes or until translucent and starting to caramelise.', 'Stir through chilli and cook, stirring occasionally, for another 2 minutes. Reduce heat to low and pour in the cream. Gently stir to combine. Simmer very gently, stirring occasionally, for 5 minutes.', 'Add cheese and stir constantly for 1 minute until cheese is melted and sauce becomes creamy.', 'Season with salt flakes and freshly ground black pepper and serve with corn chips.' ],
    ARRAY[ '10 min', '15 min', '4','easy' ], 
    'Botanas'
), (
    'Pescadillas (crispy fish tacos)', 
    'https://images.ctfassets.net/lwwf0cid7sw8/19ZZ6UrYzn7Tl98iPsB9e5/b8fe4b0cb43e9014780bc279d9826968/sticky-pork-neck-soft-tacos-with-pickled-cabbage-76743-2.jpg', 
    ARRAY[ '1 tbs extra virgin olive oil', '1 onion (finely chopped)', '1 garlic clove (crushed)', '3 tomatoes (finely chopped)', 'Shredded cabbage + lime wedges and hot sauce (to serve) Vegetable oil (to deep-fry)', '12 corn tortillas', '350g skinless & boneless white fish fillets (cut into large chunks)' ],
    ARRAY[ 'Heat oil in a large frypan over medium heat. Cook the onion for 3 minutes, stirring occasionally, until it becomes translucent. Add the garlic and cook for another minute.', 'Stir in the tomato, season with salt flakes and freshly ground black pepper, then cook, stirring occasionally, for 8-10 minutes, allowing the flavours to meld together, until tomato is soft.', 'Add fish and cook for 5-7 minutes until the fish is cooked through and flakes easily with a fork. Break up fish, but not too much, as you want chunky bits of fish in the pescadillas.', 'You also want the fish filling to be dry, so cook for another 2-3 minutes until the sauce reduces and there’s no more liquid left. Check seasoning.', 'Warm tortillas in batches in a dry frypan over medium heat until pliable, wrapping them in a tea towel as you go.', 'To assemble pescadillas, add about 1/4 cup of the fish mixture to a tortilla, fold in half and gently secure sides with 2 toothpicks. Repeat with remaining tortillas and fish mixture.', 'Heat 5cm vegetable oil in a large saucepan over medium-high heat until 180°C (a cube of bread will turn golden in 60 seconds when the oil is hot enough).', 'Deep-fry pescadillas in batches for 2 minutes or until crispy and light golden. Drain on paper towel. Discard toothpicks.', 'Serve the hot, fried pescadillas with shredded cabbage on top, with lime wedges and hot sauce for spooning over.' ],
    ARRAY[ '30 min', '10 min', '12', 'medium' ],
    'Botanas'
), (
    'Mexican roast beef', 
    'https://images.ctfassets.net/lwwf0cid7sw8/2PHdCbMfZgKirTySglp1bH/c82ee7c206565695d15faa274c02b0b5/mexican-roast-beef-with-hot-sauce-and-spicy-sweet-potato-wedges-25924-3.jpg', 
    ARRAY[ '1 garlic clove, crushed', '1 teaspoon smoked paprika (pimenton)', '1 teaspoon ground chipotle chilli', 'Juice of 2 limes', '100ml tequila', '1 1/2 teaspoons ground cumin', '1/2 cup (125ml) olive oil', '1kg beef eye fillet, trimmed', '1 red capsicum', '1 jalapeno', '2/3 cup (165ml) tomato sauce', '1/4 cup (60ml) orange juice', '2 tablespoons Worcestershire sauce', '1 tablespoon balsamic vinegar', '1 teaspoon chilli powder', '1/4 cup (60ml) olive oil', '1 teaspoon sweet paprika', '1 teaspoon garlic powder', '3 sweet potatoes, cut into wedges' ],
    ARRAY[ 'Combine garlic, paprika, chipotle chilli, lime juice, tequila, 1 teaspoon cumin and 2 tablespoons oil in a bowl. Add beef, turn to coat, then cover and chill for 3 hours to marinate.', 'Bring the beef to room temperature and preheat the oven to 200°C. For the wedges, combine oil, paprika and garlic powder in a small bowl, season, then brush over sweet potato. Bake on a baking tray for 25 minutes or until tender.', 'Meanwhile, drain the beef. Heat 2 tablespoons oil in a large frypan over high heat, then cook beef, turning, for 3-4 minutes until browned.', 'Transfer to a baking tray and roast in the oven for 15 minutes for rare or until cooked to your liking. Remove from the oven and rest, loosely covered with foil, for 10 minutes.', 'To make hot sauce, preheat the grill to high. Grill capsicum and jalapeno, turning, for 3-4 minutes until the skins are blackened and blistered. Transfer to a plastic bag, or place in a bowl and cover with plastic wrap, and set aside to cool.', 'Remove skins and seeds, and cut flesh into thick strips. Transfer to a food processor with tomato sauce, orange juice, Worcestershire sauce, vinegar, chilli powder and remaining 1/2 teaspoon ground cumin and 2 tablespoons oil, then whiz until smooth.', 'Reheat before serving.', 'Slice the beef and serve with the hot sauce, sweet potato wedges and tomato salsa.' ],
    ARRAY[ '10 min', '50 min', '4', 'easy' ], 
    'Platillos'
);